name: Commit Message and Branch Name Check

on: [push, pull_request]

jobs:
  commit-message-and-branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get install git

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Check commit messages
        run: |
          #!/bin/bash
          commit_regex="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .+"
          commits=$(git log --format=%s ${{ github.event.before }}..${{ github.sha }})
          for commit in $commits
          do
            if [[ ! $commit =~ $commit_regex ]]; then
              echo "Commit message '$commit' does not match the required format."
              exit 1
            fi
          done

      - name: Check branch name
        run: |
          #!/bin/bash
          branch_regex="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)-.+"
          branch_name=${GITHUB_HEAD_REF}
          if [[ ! $branch_name =~ $branch_regex ]]; then
            echo "Branch name '$branch_name' does not match the required format."
            exit 1
          fi